### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by MPNull** [robsdedude/southpark-downloader#6] opened 2020-07-18 09:54 UTC
I've started to download Season 1.

```
[southpark.cc.com] s01e13-cartmans-mom-is-a-dirty-slut: Downloading webpage
ERROR: 'NoneType' object has no attribute 'split'
```

**Comment by robsdedude** [comment] 2020-07-18 14:30
What version of youtube-dl do you have?  
Type `youtube-dl --version` in your command line.

**Comment by MPNull** [comment] 2020-07-18 19:01
> What version of youtube-dl do you have?
> Type `youtube-dl --version` in your command line.

2019.01.17 from apt repository.

**Comment by robsdedude** [comment] 2020-07-19 07:50
Yeah, no. See, youtube-dl uses a web scraper to find the URI of the video to download. And as web pages regularly change their layout, youtube-dl tends to fail if it's too old. Don't rely on apt repositories for that. They oftentimes are too outdated. Luckily youtube-dl is easy to install manually, as it is a pure python script. Just follow those instructions: [https://github.com/ytdl-org/youtube-dl#installation](https://github.com/ytdl-org/youtube-dl#installation).

I'll close the issue, as I'm pretty sure that this is the cause of the error. If the error persists with updated youtube-dl, feel free to reopen the issue.

**Closed as completed** 2020-07-19 07:51 UTC

**Comment by MPNull** [comment] 2020-07-19 14:30
Now I'd have latest YTDL, but the same occurs. It has something to do with it, not your script.

**Comment by SSutherland94** [comment] 2020-08-31 22:23
Having the same issue with youtube-dl 2020.07.28. I installed it following the GitHub instructions. macOS 10.15.6

**Comment by robsdedude** [comment] 2020-09-05 09:45
Hrmpf. Still think it's a youtube-dl problem. Might have something to do with region locks…  
To rule out that it's my script:
 - Update southpark-download (I just added more debug output)
 - Find an episode that does not work with `get_episodes.sh xx ll yy` where `xx` is a season (e.g. `20`), `ll` the language (e.g. `en`), and `yy` is the episode (e.g. `2`).
 - Open `get_episodes.sh` and change `DEBUG=false` to `DEBUG=true`
 - Run `get_episodes.sh` with the same parameters again and post the output here, please. I'd also like to know from which country you try to download.
 - The output should include something like 
   ```
   Downloading episodes
   Episodes https://southpark.cc.com/full-episodes/s20e02-skank-hunt#source=6154fc40-b7a3-4387-94cc-fc42fc47376e:879fd28e-c96b-4f9d-a437-e05c1bcf80aa&position=2&sort=!airdate
   ```
 - Use that URL after "Episodes" and try to run `youtube-dl InsertUrlHere`. Does that work? If not it's probably not in my hand.
 - You could also try to open that URL in you browser and see if you can watch the episode.

**Comment by SSutherland94** [comment] 2020-09-08 23:24
Well I think I found the problem. SP Studios, at least here in the states, isn't making all episodes available. So I apologize. Your script is probably fine. I downloaded the pilot (failed to join parts), but the rest of Season 1 is unavailable
